<!--#include virtual="/authenticate.inc"-->

<!-- header table -->

<%
light = "background='/graphics/back_light.jpg'"
dark = "background='/graphics/back_dark.jpg'"
gold = "bgcolor='#FFCC00'"
%>

<html>
<body background="/graphics/back_dark.jpg" link="#443333" vlink="#443333" alink="#FFCC00">

<table width="100%" border="0" cellspacing="0" cellpadding="5" <%=gold%>>
<tr>
	<td><font face="arial" size=4>