<%
' Copyright 1999 Jason Abbott (jabbott@uidaho.edu)
' Last updated 10/15/98

dim query, bc, comments, status, body

' UPDATE DATABASE

if Request.Form("close") = "on" then
	status = "closed"
	query = query 	& "technician = '" & Request.Form("technician") & "', " _
		& "time_spent = '" & Request.Form("time_spent") & "', " _
		&" complete_time = '" & Now & "', "
else
	status= "pending"	
end if

query = "UPDATE helpdesk SET "

' response.write Request.Form("comments_new") & "<p>" & Request.Form("comments_old") & "<p>"

if Request.Form("comments_new") <> "" then
	comments = replace(Request.Form("comments_new"), "'", "’")
	if Request.Form("comments_old") <> "" then
		comments = "[" & Request.Form("technician") & " " & Now & "]" & VbCrLf _
			& comments & VbCrLf & VbCrLf & Request.Form("comments_old")
	else
		if Request.Form("close") <> "on" then
			comments = "[" & Request.Form("technician") & " " & Now & "]" & VbCrLf & comments
		end if
	end if
	query = query & "comments = '" & comments & "', "
end if

query = query _
	& "status = '" & status & "' " _
	& "WHERE (id)=" & Request.Form("id")

Set db = Server.CreateObject("ADODB.Connection")
db.Open "bc"
db.Execute(query)

set JMail = Server.CreateObject("JMail.SMTPMail")
JMail.ServerAddress = "borah.engboi.uidaho.edu"
JMail.Sender = "help@borah.engboi.uidaho.edu"
JMail.SenderName = "Boise Center HelpDesk"
JMail.Subject = "Help Request Update"
JMail.AddHeader "Originating-IP", Request.ServerVariables("REMOTE_ADDR")
JMail.AddRecipientCC Request.Form("submitter_email_name") & "@" & Request.Form("submitter_email_site")

%>
<!--#include file="technician_mail.inc"-->
<%

body = "The request involving '" & Request.Form("category") _
	& "' submitted on " _
	& Request.Form("submit_time") & " by " _
	& Request.Form("submitter_first") & " " _
	& Request.Form("submitter_last") _
	& " has been "

if status = "closed" then
	body = body & "CLOSED."
elseif status = "pending" then
	body = body & "UPDATED."
end if

if comments <> "" then
	body = body & VbCrLf & VbCrLf _
		& "These comments have been entered into the database:" & VbCrLf _
		& "----------------------------------------" & VbCrLf _
		& comments & VbCrLf _
		& "----------------------------------------"
end if

if Request.Form("description") <> "" then
	body = body & VbCrLf & VbCrLf & VbCrLf & Request.Form("submitter_first") _
		& " described the problem as:" & VbCrLf _
		& "----------------------------------------" & VbCrLf _
		& Request.Form("description") & VbCrLf _
		& "----------------------------------------"
end if

body = body & VbCrLf & VbCrLf
'     & "Use this URL to view the status of your request on the web:" & VbCrLf _
'    & "http://boise.uidaho.edu/help/help_detail?id="

if Request.Form("close") = "on" then
		body = body & "If you have any questions about or would like to comment on the solution provided please send e-mail to help@borah.engboi.uidaho.edu.  "
end if

body = body & "This message was generated by the Boise Center Help Desk.  To view your request online visit http://boise.uidaho.edu/help/help_detail.asp?id=" & Request.Form("id") & "."

JMail.Body = body
on error resume next
JMail.Execute
if err = 0 then
	response.redirect "help_search.asp"
else
	response.write err.description
end if

db.Close
%>