<%
' Copyright 1998 Jason Abbott (jabbott@uidaho.edu)
' Last updated 03/24/98

' UPDATE DATABASE

query = "UPDATE helpdesk SET " _
	& "status = '" & Request.Form("status") & "', " _
	& "technician = '" & Request.Form("technician") & "', " _
	& "time_spent = '" & Request.Form("time_spent") & "', " _
	& "comments = '" & replace(Request.Form("comments"), "'", "’") & "', " _
	&" complete_time = '" & Now & "'"
	
query = query & " WHERE (id)=" & Request.Form("id")

Set db = Server.CreateObject("ADODB.Connection")
db.Open "bc"
db.Execute(query)

' NOTIFY TECHNICIANS BY MAIL

query = "SELECT * FROM employee WHERE " _
	& "email_name = '" & Request.Form("technician") & "'"

set rs = db.Execute(query)

Set mailer = Server.CreateObject("SMTPsvg.Mailer")
mailer.FromName = rs("name_first") & " " & rs("name_last")
mailer.FromAddress = rs("email_name") & "@" & rs("email_site")
mailer.RemoteHost = "borah.engboi.uidaho.edu"
mailer.AddRecipient "Jason Abbott","jabbott@uidaho.edu"
mailer.AddRecipient "Diane Griffitts","dianeg@uidaho.edu"
mailer.AddRecipient "Norm Galey","ngaley@uidaho.edu"
mailer.AddCC Request.Form("submitter_first") & " " & Request.Form("submitter_last"), _
	Request.Form("submitter_email_name") & "@" & Request.Form("submitter_email_site")
mailer.Subject = "Help Request Update"

body = "The request involving '" & Request.Form("category") _
	& "' submitted on " _
	& Request.Form("submit_time") & " by " _
	& Request.Form("submitter_first") & " " _
	& Request.Form("submitter_last") _
	& " has been updated to a status of " _
	& Request.Form("status") & " by " _
	& rs("name_first") & " " & rs("name_last") & "."

if Not Request.Form("description") = "" then
	body = body & VbCrLf & VbCrLf & Request.Form("submitter_first") _
		& " described the problem as:" & VbCrLf _
		& Request.Form("description")
end if

if Not Request.Form("comments") = "" then
	body = body & VbCrLf & VbCrLf & rs("name_first") _
		& " entered these comments into the database:" & VbCrLf _
		& Request.Form("comments")
end if

body = body & VbCrLf & VbCrLf _
	& "This message was generated by the Boise Center Help Desk.  Please visit http://boise.uidaho.edu/help to submit a new request or review past or current requests."

mailer.BodyText = body

mailer.SMTPLog = "c:\internet\mail\smtp.log"
if Mailer.SendMail then
	response.redirect "help_search.asp"
else
%>
	<!--#include file="smtp_log.inc"-->
<%
end if
db.Close
%>